### ISSUE TITLE
Error in same case

### ISSUE THREAD

**Issue by levipadre** [KOBENDigital/ConditionalDisplayers#10]
Hi,

My case: I have 4 fields and the switcher. Two-two fields for visible and hidden states.

I switched to hidden (false) and filled the two fields in then saved.
From this point I couldn't use the switcher anymore.
On devtoolbar I can see this error:
<img width="766" alt="Screenshot 2019-09-25 at 13 21 25" src="https://user-images.githubusercontent.com/357974/65600155-7e16f400-df97-11e9-914e-37419de6e11d.png">

Should I rename something (datatype or doctype) to make it work?

Thanks!

**Comment by skartknet** [comment]
This will have to wait till Monday. I don't have a computer at hand.

**Comment by skartknet** [comment]
Try going to '/app_plugins/conditionaldisplayers/propertyeditors/checkbox/checkbox.controller.js'
And in line 69 replace 'angular.lowercase($scope.model.value) === "true"' for '$scope.model.value===true'

**Comment by levipadre** [comment]
Thanks for the support! It did work.

If you could also do #9 at some point, that would be perfect.

**Comment by skartknet** [comment]
fixed in v2.2.1

**Comment by michaelchart** [comment]
@skartknet I've installed v2.3.0 via nuget and this error seems to still be present (angular.lowercase is not a function). Did this fix make it into the release?

**Comment by skartknet** [comment]
Hmmm, it should be fixed. I'll take a look.

**Comment by skartknet** [comment]
I just published the version 2.3.1 as a Nuget. It should be fixed there.
