### ISSUE TITLE
NuGet package dependencies

### ISSUE THREAD

**Issue by tomvanenckevort** [KOBENDigital/ConditionalDisplayers#14]
I was about to upgrade the package from v2.3.0 to v2.3.1 via NuGet in our project, but then I noticed the list of dependencies has changed in v2.3.1.

Whereas in v2.3.0 it only required `UmbracoCms.Core >=8.2.1`, in v2.3.1 the list of dependencies is a lot longer (it includes AutoMapper, Log4Net and some ASP.NET libraries for example).

Was that an intentional change, or is it maybe a bug when the updated NuGet package/nuspec was generated?

**Comment by skartknet** [comment]
Hi Tom, that is a bug when the dependencies were generated. You can open the package and remove them if you don't want them installed.

**Comment by tomvanenckevort** [comment]
Hi Mario. Yes, that is an option, but wouldn't work if you're using a CI/CD process where the project gets rebuilt every time and the NuGet packages get restored as part of the process (which is what we do).

It's not a major issue, but just something I noticed while attempting the upgrade, so I just wanted to make you aware of it in case you hadn't noticed 🙂

**Comment by skartknet** [comment]
You're right. Thanks for letting me know,  I'll try to upload a new version soon.

**Comment by skartknet** [comment]
I have uploaded a v2.3.2 with only Umbraco.Core as dependency.
