### ISSUE TITLE
Umbraco 8.7: Hidden properties are hidden in the designer as well

### ISSUE THREAD

**Issue by robertjf** [KOBENDigital/ConditionalDisplayers#16]
When you have a ConditionalDisplayer property and use it to hide properties if it's unchecked,  the properties will be hidden in the designer as well.

This works:

![image](https://user-images.githubusercontent.com/818101/93270187-e471d380-f7f3-11ea-8fa5-0e9409714d44.png)

This doesn't work:

![image](https://user-images.githubusercontent.com/818101/93270158-d623b780-f7f3-11ea-99e2-9370cb8917ee.png)

**Comment by skartknet** [comment]
Fixed on 2,3.4
