### ISSUE TITLE
Typed model always returns 0 instead of boolean

### ISSUE THREAD

**Issue by ReVoid** [KOBENDigital/ConditionalDisplayers#2]
Hi, Mario

Field of Checkbox type always return 0, doesn't matter true or false was set in a backoffice Umbraco 7.12.4

Great package, but useless when you need to use it as a boolean like condition of rendering something with razor

I think, making boolean as $scope.model.value would be much better and usefull.

Thanks. Dmitriy.

**Comment by skartknet** [comment]
Oh no! That's not good. I'll try to fix it soon. thanks for letting me know.

**Comment by ReVoid** [comment]
> Oh no! That's not good. I'll try to fix it soon. thanks for letting me know.

Your welcome. 
Unfortunatly, I did't test dropdown conditional displayer prepery editor for that bug. 

And one more thing :) Missing semicolons [here](https://github.com/KOBENDigital/ConditionalDisplayers/blob/master/src/ConditionalDisplayers/App_Plugins/ConditionalDisplayers/propertyeditors/checkbox/checkbox.controller.js) in the end of 1-st row 

Thanks

**Comment by skartknet** [comment]
This has been fixed on version 1.2.0

**Comment by ReVoid** [comment]
Alarm!

Toggle is broken now :(
![image](https://user-images.githubusercontent.com/12345710/52129170-ef401a80-2647-11e9-8755-3e6aacb13b59.png)
