### ISSUE TITLE
Config values parsing error when it empty

### ISSUE THREAD

**Issue by ReVoid** [KOBENDigital/ConditionalDisplayers#3]
v.1.2.0

If developer did't filled config values of property editor, the UI toogle does't working and there is a console error on backoffice ui loading: 
![image](https://user-images.githubusercontent.com/12345710/52129889-c751b680-2649-11e9-8d54-88593a5e0df9.png)

Checking for null would reduce developers panic =)
I

**Comment by skartknet** [comment]
Somehow I missed this ticket for so long, sorry for that. I have fixed the issue and a new version is up.
