### ISSUE TITLE
Turn value to true itself if it false on page save or publish v.1.2.0

### ISSUE THREAD

**Issue by ReVoid** [KOBENDigital/ConditionalDisplayers#4]
Alarm! 

When you don't turn toggle to true yourself, it turns itself on umbraco page saving or publishing.

**Comment by skartknet** [comment]
Are you serious!? I tested it many times!! :'/

**Comment by skartknet** [comment]
Fixed on v1.3 Please give it a try.

**Comment by ReVoid** [comment]
> Fixed on v1.3 Please give it a try.

Woohoo! Works now =)
