### ISSUE TITLE
No strongly typed values in model

### ISSUE THREAD

**Issue by ReVoid** [KOBENDigital/ConditionalDisplayers#5]
When working with property on backend it returns always object value.
It forced developers to use _**Model.GetPropertValue<bool>**_ syntax instead of strongly typed 

```
if(Model.MyConditionalDisplayer)
{ 
     // something cool
}
```

Would be perfect to use both ways

**Comment by skartknet** [comment]
This should be fixed on v1.2 with the value converter. My internal tests are done using the strongly typed mode.

**Comment by ReVoid** [comment]
> This should be fixed on v1.2 with the value converter. My internal tests are done using the strongly typed mode.

May be something went wrong with nuget update in my case, i didn't notice adding adding value converters. I will re-check

**Comment by skartknet** [comment]
Weird. I'll check the package as well.

**Comment by ReVoid** [comment]
> Weird. I'll check the package as well.

I have checked now on version 1.3.0 with nuget in steps:
Delete existing package
Install new package
Rebuild models

And...editors returns objects :( 

But next, I overrided the package from backoffice package install section.
And....now it returns bool as expected.

I can't explain that behavior.
Where can I find the value converter dll in solution?

**Comment by skartknet** [comment]
Hey @ReVoid are you still having this issue?

**Comment by ReVoid** [comment]
> Hey @ReVoid are you still having this issue?

I can't check it  soon, sorry. So, I don't know :(

**Comment by skartknet** [comment]
No problem.  I'll close it for now.  Please reopen it if the issue persists.
