### ISSUE TITLE
Nested Content inside of Stacked Content

### ISSUE THREAD

**Issue by bgunnarsson** [KOBENDigital/ConditionalDisplayers#7]
I have a CD checkbox inside a nested content item which is then inside of a stacked content item and no fields are hidden, everything is shown (default). I'm currently checking if I can fix the issue.

**Comment by skartknet** [comment]
ConditionalDisplayers uses the 'data-element' attribute to target the elements. You should check if the properties in Nested Content or Stacked Content are missing that attribute.

![image](https://user-images.githubusercontent.com/1685262/62332360-9c65f380-b502-11e9-87b3-9f5f0c76d974.png)

**Comment by bgunnarsson** [comment]
You're right, they are missing that data attribute.
![nc](https://user-images.githubusercontent.com/2563119/62357620-f961a980-b502-11e9-9b0b-08e439f1df77.PNG)

**Comment by bgunnarsson** [comment]
I'm currently working on a fix that I will then be creating a PR for in the Umbraco-CMS core repo.

**Comment by bgunnarsson** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/6150

**Comment by bgunnarsson** [comment]
If this will be merged before 7.15.2 then if you want to use this package with NestedContent then the minimum version will be 7.15.2.
The data-attribute will be like this -> data-property="property-nested___[alias]"

**Comment by skartknet** [comment]
Thanks @bgunnarsson but not sure if Umbraco will release new 'features' any more. I think they will just support v7 for a few years and will only release security patches.

**Comment by bgunnarsson** [comment]
I'm pretty baffled by that they marked this as a feature since it's clearly an oversight - The normal property editors have this and not the NestedContent ones which in turn breaks this package and other packages that rely on that data-attribute. A clear bug in my books.

**Comment by bgunnarsson** [comment]
IF this gets fixed in v8 then great. I'll just handle v7 differently

**Comment by skartknet** [comment]
You're right, I think they should release bugs fixes while they give support to v7. Anyways, I'm sure this will be fixed on v8.

**Comment by bgunnarsson** [comment]
This will be coming in 7.15.3 and 8.1.4 👍
