### ISSUE TITLE
Ignore required state for hidden fields

### ISSUE THREAD

**Issue by levipadre** [KOBENDigital/ConditionalDisplayers#9]
Hi,

Is it possible somehow to ignore required fields? When I hide a few fields "under" the conditional switcher and they are required, I can't save the page.
It would be great if the active "visible" state can control the fields under it.

**Comment by skartknet** [comment]
Yes, that'd be good. That's not supported. I'll keep this ticket open so I don't forget to  take a look.

**Comment by levipadre** [comment]
Do you think this required field support will happen any time soon? It would be really useful in my project. I don't think I can find similar package at all.

**Comment by skartknet** [comment]
Sorry but my free time is not too much. I'll do my best to have a solution soon but you should probably think of other alternatives. Is it that important that those fields are mandatory? I mean they will offer a better user experience but you probably go ahead without them being mandatory.

**Comment by levipadre** [comment]
Yeah, I totally understand it. No other alternative unfortunately, but maybe the required fields won't be a big problem. If you don't have enough time, I assume it wouldn't help if I compensate your time a bit. If do so, please let me know.

**Comment by skartknet** [comment]
I have tried today and I managed to toggle the validation in the frontend but 'unfortunately' Umbraco validates the model before saving so it returns an error. So I'm afraid to say that at this point that's not going to work.

**Comment by levipadre** [comment]
Thank you for your time and effort, it’s very kind of you.

Btw, isn’t it possible by adding disabled attribute to the fields temporarily which are required? As I know the form shouldn’t send disabled fields to server.

I’ve also read something about a no-dirty-check attribute here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/89316-you-have-unsaved-changes-in-custom-dashboard , but maybe it’s a different case.

**Comment by skartknet** [comment]
Yes, but that disables the frontend validation. The issue now lies in that the server is also validating the form, it uses the doctype values to do so and if a value is mandatory it will return an error.
